# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNToasty' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNToasty

  pod 'Toast', '~> 4.0.0'
end
